# Generated by Django 5.1 on 2024-08-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='outpur_urls',
            new_name='output_urls',
        ),
    ]
